<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Test_User_Login" time="24" tests="0" failures="2" errors="0">
   <testsuite name="Test_User_Login" tests="0" failures="2" errors="0" time="24" timestamp="2018-05-08 21:30:53" hostname="snailwalker - 192.168.0.101" id="Test Suites/Test_User_Login">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051"/>
         <property name="logFiles" value="/Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051/execution0.log"/>
         <property name="attachments" value="/Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051/1525789865439.png, /Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051/1525789877761.png"/>
         <property name="hostName" value="snailwalker - 192.168.0.101"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="5.4.1.1"/>
         <property name="browser" value="Chrome 66.0.3359.139"/>
         <property name="hostAddress" value="192.168.0.101"/>
         <property name="sessionId" value="c6ec192a350d51a3623239982eaee0d3"/>
         <property name="seleniumVersion" value="3.7.1"/>
         <property name="proxyInformation" value="ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/Test User Login" classname="Test Cases/Test User Login" status="FAILED">
         <failure type="FAILED" message="Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)"/>
         <system-out><![CDATA[2018-05-08 21:30:54 - [TEST_CASE][FAILED] - Test Cases/Test User Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-05-08 21:30:54 - [TEST_STEP][PASSED] - openBrowser: Browser is opened with url: ''

2018-05-08 21:30:57 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-05-08 21:30:57 - [TEST_STEP][PASSED] - navigateToUrl: Navigate to 'http://34.209.48.20:9089/' successfully

2018-05-08 21:31:05 - [MESSAGE][PASSED] - Navigate to 'http://34.209.48.20:9089/' successfully

2018-05-08 21:31:05 - [TEST_STEP][PASSED] - verifyElementPresent: Object 'Object Repository/all_Objects/header' is present

2018-05-08 21:31:05 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-05-08 21:31:05 - [MESSAGE][PASSED] - Object 'Object Repository/all_Objects/header' is present

2018-05-08 21:31:05 - [TEST_STEP][PASSED] - verifyElementPresent: Object 'Object Repository/all_Objects/p_header_description' is present

2018-05-08 21:31:05 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-05-08 21:31:05 - [MESSAGE][PASSED] - Object 'Object Repository/all_Objects/p_header_description' is present

2018-05-08 21:31:05 - [TEST_STEP][FAILED] - verifyElementPresent: Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-05-08 21:31:05 - [MESSAGE][WARNING] - Test object with id 'Object Repository/User Login/h2_Login' does not exist

2018-05-08 21:31:05 - [MESSAGE][WARNING] - Test object with id 'Object Repository/' does not exist

2018-05-08 21:31:06 - [MESSAGE][FAILED] - Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)
[[ATTACHMENT|/Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051/1525789865439.png]]]]></system-out>
         <system-err><![CDATA[2018-05-08 21:30:54 - [TEST_CASE][FAILED] - Test Cases/Test User Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-err>
      </testcase>
      <testcase name="Test Cases/Test User Login" classname="Test Cases/Test User Login" status="FAILED">
         <failure type="FAILED" message="Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)"/>
         <system-out><![CDATA[2018-05-08 21:31:06 - [TEST_CASE][FAILED] - Test Cases/Test User Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-05-08 21:31:06 - [TEST_STEP][PASSED] - openBrowser: Browser is opened with url: ''

2018-05-08 21:31:06 - [MESSAGE][WARNING] - A browser is already opened. Closing browser and opening a new one

2018-05-08 21:31:07 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-05-08 21:31:07 - [TEST_STEP][PASSED] - navigateToUrl: Navigate to 'http://34.209.48.20:9089/' successfully

2018-05-08 21:31:17 - [MESSAGE][PASSED] - Navigate to 'http://34.209.48.20:9089/' successfully

2018-05-08 21:31:17 - [TEST_STEP][PASSED] - verifyElementPresent: Object 'Object Repository/all_Objects/header' is present

2018-05-08 21:31:17 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-05-08 21:31:17 - [MESSAGE][PASSED] - Object 'Object Repository/all_Objects/header' is present

2018-05-08 21:31:17 - [TEST_STEP][PASSED] - verifyElementPresent: Object 'Object Repository/all_Objects/p_header_description' is present

2018-05-08 21:31:17 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-05-08 21:31:17 - [MESSAGE][PASSED] - Object 'Object Repository/all_Objects/p_header_description' is present

2018-05-08 21:31:17 - [TEST_STEP][FAILED] - verifyElementPresent: Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)

2018-05-08 21:31:17 - [MESSAGE][WARNING] - Test object with id 'Object Repository/User Login/h2_Login' does not exist

2018-05-08 21:31:17 - [MESSAGE][WARNING] - Test object with id 'Object Repository/' does not exist

2018-05-08 21:31:18 - [MESSAGE][FAILED] - Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)
[[ATTACHMENT|/Users/snailwalker/Documents/workspace/backend/katalon/Reports/Test_User_Login/20180508_213051/1525789877761.png]]]]></system-out>
         <system-err><![CDATA[2018-05-08 21:31:06 - [TEST_CASE][FAILED] - Test Cases/Test User Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-err>
      </testcase>
      <system-out><![CDATA[2018-05-08 21:30:53 - [TEST_SUITE][FAILED] - Test_User_Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-out>
      <system-err><![CDATA[2018-05-08 21:30:53 - [TEST_SUITE][FAILED] - Test_User_Login: Test Cases/Test User Login FAILED because (of) Unable to verify object is present (Root cause: java.lang.IllegalArgumentException: Object is null)]]></system-err>
   </testsuite>
</testsuites>
